services:
  - type: web
    name: laboratorio14-app
    env: dotnet
    plan: free
    region: ohio
    buildCommand: dotnet restore && dotnet publish -c Release -o output
    startCommand: cd output && ./Laboratorio14
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000